# This is a basic workflow to help you get started with Actions

name: fetch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run:  curl https://www.city.setagaya.lg.jp/mokuji/kusei/001/001/004/d00185364.html > data.html

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git config --local user.email "frogcat@users.noreply.github.com"
        git config --local user.name "frogcat-bot"
        git add data.html
        git commit -m "Update data.html"

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
