# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: html2csv

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
    - run: git config --local user.email "frogcat@users.noreply.github.com"
    - run: git config --local user.name "frogcat-bot"
    - run: git add docs/data.csv
    - run: git commit -m "Update data.csv"

    - name: GitHub Push
      if: ${{ success() }}
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
